### ISSUE TITLE
Include babel-runtime in devDependencies

### ISSUE THREAD

**Issue by imjared** [ramsaylanier/WordpressExpress#1]
morning! this looks rad and i'm looking forward to toying with it.

anyways, i was getting a bunch of love from terminal this morning:

```
ERROR in ./app/App.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in /Users/jaredlaser/sites/playground/WordpressExpress/app
 @ ./app/App.js 7:22-78

ERROR in ./app/App.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in /Users/jaredlaser/sites/playground/WordpressExpress/app
 @ ./app/App.js 11:23-70

etc.
```

`$ npm i babel-runtime --save-dev` cleaned this up for me. more than happy to send a PR if you're into that sort of thing but it's one line :)

**Comment by ramsaylanier** [comment]
Thanks. Must have overlooked this one. I'll add it!
