### ISSUE TITLE
Rest API vs Sequelize.js vs graphql-php

### ISSUE THREAD

**Issue by ghost** [ramsaylanier/WordpressExpress#15]
Hi @ramsaylanier 

I looked through your project and I am wondering whether there is a necessity to use Sequelize and in general - the idea of mapping Wordpress database.

Namely, what if we would use WP REST API in resolve() instead of Sequelize?
http://v2.wp-api.org/
So, instead of this function implementation:

```
getPostById(postId){
        return Post.findOne({
          where: {
            id: postId
          }
        })
      },
```

we would return the result by hitting the appropriate endpoint defined here: http://v2.wp-api.org/reference/posts/

As far as I understand, `Post.findOne` will ask for the whole post and then filter a result before sending it to the client, isn't it? If true, wouldn't it just easier to would to hit appropriate endpoints in your solution? I might missing something, so please correct me if I'm wrong.

Cheers,

**Comment by ramsaylanier** [comment]
You absolutely could use the WP API if you want. There are several reasons I think Sequelize is a better choice. I think its easier to create your own custom endpoints using Sequelize if you understand how Javascript Promises work. Sequelize automatically returns Promises which work really well with Relay/GraphQL. If you wanted to, say, get a post and then its thumbnail using the API you' have to create your own Promise chain to first query the Post, get its thumbnail ID, then query Media. 

Also, you can define model relationships with Sequelize. Where you query a post by its slug in the resolve function you can automatically get all (or some) of that post's postmeta. How do you get custom post meta using the API? I'm seriously asking - I just looked through the documentation briefly but I didnt see it. 

But, to answer your question you absolutely could use the WordPress API instead of Sequelize. That's the beauty of GraphQL. You have the power to get data from  your data store however you want.

**Comment by ghost** [comment]
> You absolutely could use the WP API if you want. There are several reasons I think Sequelize is a better choice. I think its easier to create your own custom endpoints using Sequelize if you understand how Javascript Promises work. Sequelize automatically returns Promises which work really well with Relay/GraphQL. If you wanted to, say, get a post and then its thumbnail using the API you' have to create your own Promise chain to first query the Post, get its thumbnail ID, then query Media.

Yes, you are right, Promises should be returned for REST calls. However, if such a mechanism would be applied, then I understand that the effect would be the same, just calling the appropriate rest endpoint for getting Posts and calling the appropriate endpoint for getting Thumbnail from Media in resolve functions. The chain will be ensured by GraphQL.

> Also, you can define model relationships with Sequelize. Where you query a post by its slug in the resolve function you can automatically get all (or some) of that post's postmeta. How do you get custom post meta using the API? I'm seriously asking - I just looked through the documentation briefly but I didnt see it.

Here, you are right once again. This REST API has really limited possibilites, so getting data for customized queries is not possible. At the beginning I thought that it is an official Wordpress API and is more sophisticated.

Meanwhile, I found also the following project: [graphql-wp](https://github.com/crafttheweb/graphql-wp)
Do you consider it not to be an easier approach due to the fact that we can use built in Wordpress functions?
For instance there is one-line invocation for getting a menu:
`return wp_get_nav_menu_items($args['name']) ?: [];`

To be honest, I am asking all about that, because I am wondering what would be the best approach to apply something similar for Magento 2:
- Sequelize.js
- [Magento 2 REST API](http://devdocs.magento.com/swagger/index.html)
- or an approach like [graphql-wp](https://github.com/crafttheweb/graphql-wp), but accustomed to Magento

Magento has a much sophisticated database than in Wordpress and I think that applying Sequelize.js solution might be overwhelming in case of Magento.

**Comment by ramsaylanier** [comment]
graphql-wp is a PHP implementation, so not useful for this project though I agree it is pretty neat. However, using Sequelize, I've written a function that just takes the slug of a menu and returns all of that menu's pages and sub pages (it only goes down one level right now).

It could probably use some refactoring but here it is.

``` javascript
getMenu(name){
        return Terms.findOne({
          where: {
            slug: name
          },
          include: [{
            model: TermRelationships,
            include: [{
              model: Post,
              include: [Postmeta]
            }]
          }]
        }).then ( res => {
          if (res){
            let menu = {
              id: null,
              name: name,
              items: null,
            };
            menu.id = res.term_id;
            const relationship = res.wp_term_relationships;
            const posts = _.map(_.pluck (relationship, 'wp_post'), 'dataValues');
            const navItems = [];

            const parentIds = _.pluck(_.filter(posts, post=>{
              return post.post_parent == 0
            }), 'id');

            _.map(_.sortBy(posts, 'post_parent'), post => {
              let navItem = {};
              let postmeta = _.pluck(post.wp_postmeta, 'dataValues');
              let isParent = _.includes( parentIds, post.id);
              let linkedId = Number(_.pluck(_.filter(postmeta, meta => {
                return meta.meta_key == '_menu_item_object_id'
              }), 'meta_value'));

              if (isParent){
                navItem.id = post.id;
                navItem.order = post.menu_order;
                navItem.linkedId = linkedId;
                navItem.children = [];
                navItems.push(navItem);
              } else {
                let parentId = Number(_.pluck(_.filter(postmeta, meta => {
                  return meta.meta_key == '_menu_item_menu_item_parent'
                }), 'meta_value'));
                let existing = _.findWhere(navItems, {'id' : parentId})

                if (existing){
                  existing.children.push({id: post.id, linkedId: linkedId })
                }
              }

              menu.items = navItems;
            });

            return menu;
          }
        });
      }
    }
```

Sequelize is pretty powerful I think. I have no idea about using it with Magento though - this is my first time using Sequelize.
