### ISSUE TITLE
Does Hot Module Replacement work for Relay Containers?

### ISSUE THREAD

**Issue by ghost** [ramsaylanier/WordpressExpress#17]
I have problems with HMR. I noticed that it does not work for relay containers generated from react components. Do you have the same problem?

**Comment by ramsaylanier** [comment]
It should definitely work with HMR. My local version of this project does.

**Comment by ghost** [comment]
It was not working in my case. I do not why. I started using:
`"presets": "react-hmre"` in `.babelrc`
and now it works, but I have already noticed that it works irregular. I will try to investigate it and let you know when I get something more.

**Comment by ramsaylanier** [comment]
Have you tried cloning a fresh copy of this project? I do remember a month or so ago I noticed it wasn't working - I was trying to using BrowserSync to get React CSS Module changes to update. I ended up finding a better solution but I merged those changes a while ago.

**Comment by ramsaylanier** [comment]
See this commit: 
https://github.com/ramsaylanier/WordPressExpress/commit/207456823b4d549c9c8199be52f6255716caecb1

**Comment by ramsaylanier** [comment]
Also, are you talking about HMR when you are changing stuff inside the Relay Container? Or are you just talking about changing components wrapped in a Relay Container? 

If, for example, you are adding or removing a field from the Relay.QL fragment - no, HMR doesn't seem to work. You'll have to hard refresh to see the change.

**Comment by ghost** [comment]
I meant React Components, not Relay Containers.

I cloned the repo once again in order to try it out and I have the following error after `npm install` and `npm run startdev`:

```
Error: The (relay-query) Babel 5 plugin is being run with Babel 6.
```

There are some information about that:
https://github.com/relayjs/relay-starter-kit/issues/74
https://github.com/facebook/relay/issues/887
I will figure it out later.

**Comment by ghost** [comment]
I know how to run the project.
`babel-core@6.6.5` and `babel-relay-plugin@0.6.3` are automatically installed and they are not compatible with each other.
The solution is to change `babel-relay-plugin` manually applying [these changes](https://github.com/evenco/relay/commit/a228ff6b4ad90ed2646291994a4fafec7c15d856)
or by installing `babel-relay-plugin@0.7.3`.
The first option works, the second one also should, but I have not tried it yet. I will check now if HMR works.

**Comment by ramsaylanier** [comment]
Great! Let me know to result.

**Comment by ghost** [comment]
Yesterday, HMR was not working for me. Today, it suddenly started working. As far as I remember I was not changing anything. It is strange. If I find something more I let you know.
I use: `babel-core@6.5.2`, `babel-relay-plugin@0.6.3`, `react-relay@0.6.1`.
Cheers.

**Comment by ghost** [comment]
I noticed what was the issue. I had the following structure of components/containers:

```
/components
--- component A
------ component A1
------ component A2
--- component B
--- component C
```

HMR works always in the following components/containers: `A, B, C` and intermittently in: `A1, A2`, so it seems that I need to set any variable for HMR to work for components that are not placed directly in `/components` folder or... there is a bug in webpack plugins.

Nevertheless, I will close this issue, as there is no problem with your configuration. Thank you for the good project. :)
