### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adjourn** [ramsaylanier/WordpressExpress#19]
I get an error when running `npm run startdev` or `npm run build`:
`
Error: The (relay-query) Babel 5 plugin is being run with Babel 6.`

Also, is it still under development? Im definately going to contribute if I get it to work and wrap my head around it. Very exciting indeed.

**Comment by ramsaylanier** [comment]
See https://github.com/ramsaylanier/WordPressExpress/issues/18.

Yes, it's very much under development. I look forward to your contributions!
