### ISSUE TITLE
Replace Relay with Apollo

### ISSUE THREAD

**Issue by ramsaylanier** [ramsaylanier/WordpressExpress#21]
Soon (very soon!) I plan on completely replacing Relay with [Apollo Stack](http://www.apollostack.com/) to get reactive queries and such.

**Comment by ramsaylanier** [comment]
This is pretty much done on the Apollo branch. Need to update documentation before merging with master.

https://github.com/ramsaylanier/WordPressExpress/commit/ca3c8f12fee21f3c2526b2058540002dd74510a9

**Comment by filod** [comment]
@ramsaylanier  Can you explain why you be doing this ? 
IMHO, relay & apollo share almost the same idea, but relay provides more features.

**Comment by ramsaylanier** [comment]
@filod  Relay is definitely more mature, but there are some fundamental things that make Apollo more attractive to me. First, the idea that Apollo will offer reactive GraphQL queries is pretty nice. Any changes to the database will trigger query refetching. I'm not sure of their current progress, but I know they currently offer the option to "poll and diff" queries. Second, Relay currently has [limitations on the root query which Apollo doesn't](https://github.com/apollostack/apollo-client/issues/304).

**Comment by ramsaylanier** [comment]
I've merged the Apollo branch into master, and I have deployed it to http://wordexpress.io!
