### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by timscott** [ramsaylanier/WordpressExpress#24]
Would it be possible to enable cross origin requests? Here's an example of how it's done with express: https://github.com/expressjs/cors#simple-usage-enable-all-cors-requests

I guess that would added here: https://github.com/ramsaylanier/WordExpress/blob/master/server.js#L12

But maybe it should be configurable? I'm not sure the best way to accomplish that. Happy to make a PR. Alternatively, we can just fork.

**Comment by ramsaylanier** [comment]
Its certainly possible to add CORS support, though I think it should 1) be a configuration option and 2) should be done on a fork. You can probably just add it to the configuration json file in the```settings``` directory and then reference that configuration in ```server.js```
