### ISSUE TITLE
wp_prefix variable doesn't get updated

### ISSUE THREAD

**Issue by JMV2112** [ramsaylanier/WordpressExpress#32]
I'm trying to change the table prefix within my dev.json file, but the prefix doesn't get updated after rebuilding and running the dev server. After looking through the `wordexpress-schema` library I noticed that everything except the prefix is getting set to a variable

    `_createClass(WordExpressDatabase, [{
        key: 'connect',
        value: function connect() {
          var _settings$privateSett = this.settings.privateSettings.database;
          var name = _settings$privateSett.name;
          var username = _settings$privateSett.username;
          var password = _settings$privateSett.password;
          var host = _settings$privateSett.host;
          var _settings$publicSetti = this.settings.publicSettings;
          var amazonS3 = _settings$publicSetti.amazonS3;
          var uploads = _settings$publicSetti.uploads;`

Then setting the wp_prefix variable like so

    `key: 'getModels',
     value: function getModels() {
         var prefix = 'wp_';
         var Conn = this.connection;`

Should the prefix variable be set dynamically as well or am I missing something?

**Comment by ramsaylanier** [comment]
Sorry for the late response! I think there was a [PR that was merged for this](https://github.com/ramsaylanier/WordExpressSchema/pull/10), but I haven't yet published a new version to npm.

Honestly, I'm waiting for ApolloStack's first 1.0 release to make any more changes, and update the npm packages. This should be soon, hopefully.

**Comment by ramsaylanier** [comment]
I think this should be fixed now.
