### ISSUE TITLE
Update to Apollo Client release Candidate

### ISSUE THREAD

**Issue by adamsoffer** [ramsaylanier/WordpressExpress#33]
LOVE THIS!

I noticed the Apollo deps are pretty out of date. Let's use the newly released apollo-client 1.0.

**Comment by ramsaylanier** [comment]
Yes, I plan on revamping this project soon now that 1.0 has been released.

**Comment by ramsaylanier** [comment]
I've updated to Apollo Client and I've updated/published the related Schema and Components packages to npm as well.

https://github.com/ramsaylanier/WordExpress/pull/34
