### ISSUE TITLE
Relay With Server Side Rendering

### ISSUE THREAD

**Issue by ramsaylanier** [ramsaylanier/WordpressExpress#9]
Item #1 on the Road Map is to get Server Side Rendering working with this project. There are issues using Relay with SSR.  @Nubuck has offered to take as stap ( see #7 )

All SSR issues lets leave in here for now.

**Comment by ramsaylanier** [comment]
@nubuck I'm going to start taking a stab at this myself as well. I think getting SSR to work will solve a lot of the layout problems I'm having as well.

**Comment by Nubuck** [comment]
@ramsaylanier the more the merrier. Please do post any findings or struggles

**Comment by alexhawkins** [comment]
isomorphic-relay-router https://www.npmjs.com/package/isomorphic-relay-router

see it implemented here https://github.com/codefoundries/isomorphic-material-relay-starter-kit

**Comment by thelordoftheboards** [comment]
The isomorphic relay router also has the ToDo example from the Facebook's own Relay re-implemented in isomorphic way: https://github.com/denvned/isomorphic-relay-router/tree/master/examples/todo

https://github.com/codefoundries/isomorphic-material-relay-starter-kit is also based on isomorphic-relay-router.

**Comment by ramsaylanier** [comment]
@alexhawkins yup - that's what I've been looking at!

**Comment by ramsaylanier** [comment]
Moved to Apollo instead of Relay.
